---
# tasks file for vpc

# Include variable file so that vpc.yml knows where to call the values of its variable
- include_vars: "vars/main.yml"
  tags: create-vpc

# Create A VPC
- name: Create AWS VPC
  amazon.aws.ec2_vpc_net:
    name: ansible-vpc
    cidr_block: "{{ cidr_block }}"
    region: "{{ region }}"
  register: aws_vpc_info
